### ISSUE TITLE
Current draft of HPC novice

### ISSUE THREAD

**Issue by zonca** [swcarpentry/hpc-novice#24]
hi!
I'm teaching a 1-day workshop on HPC at the end of May, I'd like to use HPC Carpentry material instead of preparing my own and provide some feedback and improvements.
Looking around I think the closer material to `hpc-novice` is https://github.com/psteinb/hpc-in-a-day from @psteinb.
Should I start from there or anybody has a better suggestion?
Thanks!

**Comment by psteinb** [comment]
hey @zonca, thanks for reaching out. @ChristinaLK and @shwina are currently loosely trying to bring together the hpc curriculum in swcarpentry. any help or experiences contributing to this adventure are highly appreciated. as of #19, I decided to fork the repo into [hpc-in-a-day](https://github.com/psteinb/hpc-in-a-day) and put up a workshop with good feedback. Feel free to contact me offline if you want to hear more details on how it went and what to do and what not to do. 

the current proposal by @ChristinaLK, @shwina and myself on how to move forward is to come up with 2 hpc targeted material sets within swc:
1. hpc-novice which will cover advanced terminal topics (environment, module system, file system permissions etc) and scheduler basics. it's most likely that this repo will host this material IIRC
2. hpc-parallel which will cover basic parallel programming in a HPC context. Once I have the time for it, I'll create this repo and fill it with material from [hpc-in-a-day](https://github.com/psteinb/hpc-in-a-day)

I am also in touch with a couple of HPC centers in Europe in order to get together a community behind hpccarpentry. Any help on this around here or anywhere in the world is very welcome as well.

**Comment by zonca** [comment]
Thanks @psteinb, it would be great if you could share your experience in teaching hpc in a day publicly in a blog post or something similar, I think it would help in defining the content of the class.

About the material, it looks like now all of it is in the https://github.com/psteinb/hpc-in-a-day repo, right?

**Comment by psteinb** [comment]
> Thanks @psteinb, it would be great if you could share your experience in teaching hpc in a day publicly in a blog post or something similar, I think it would help in defining the content of the class.

I have no problem with this if the community would appreciate it. 
Problem is, which blog to post it to?

> About the material, it looks like now all of it is in the https://github.com/psteinb/hpc-in-a-day repo, right?

yes. if you have any questions, either open an issue or contact me 
directly. I am happy to help.

**Comment by zonca** [comment]
What about the swcarpentry blog? I think it would be suitable

**Comment by jduckles** [comment]
@psteinb We'd love to see a post about your teaching of hpc-in-a-day! You can put the post in [`swcarpentry/website`](https://github.com/swcarpentry/website) repo in the `_posts/<year>/<month>` directory as a PR and I'll merge it to get it on the blog.

**Comment by ChristinaLK** [comment]
@zonca we outlined a lesson here + are still trying to translate that into this repo.  

https://docs.google.com/document/d/1WHPdU7_dlFRytuIJE9I3DJKCd_esiF82ZhTHIIyfRN0/edit?usp=sharing

**Comment by zonca** [comment]
I've taught my workshop yesterday, I used the digits of pi example from the hpc-in-a-day repo, I modified it using `pathlib`, removing `np.where`, using `concurrent.futures` instead of `multiprocessing` and implementing a `dask` version. If you are interested in merging any of those changes here, they are available in this folder: https://github.com/zonca/intro_hpc/tree/master/4_digits_of_pi
